# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d62824d0620330900c5d6dc6d08639374a2c13630c70e867770aae09179b02239dadbeed8a0380d087994e90a56fb22102a8ed985a56dbbb8b97f0bddf8290d
  gmail_username: "something@gmail.com"
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>

test:
  secret_key_base: e40825216283f88da11104d93a25c93a55c2e9efb0b7b320223016c45f272e9f18f1ccf61928d6f45a0f2738bcb2467aaf0b2e0606204b349074654c24698d5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: e40825216283f88da11104d93a25c93a55c2e9efb0b7b320223016c45f272e9f18f1ccf61928d6f45a0f2738bcb2467aaf0b2e0606204b349074654c24698d5b
